version: '3'
#Password: noubissie
services:
  mars-pictures:
    container_name: mars-pictures
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/home/node/app
    command: sh -c "npm run develop"
    depends_on:
      - reverse-proxy
      - strapi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.mars-pictures.local`)"
      - "traefik.port=8000"
    networks:
     - default
    
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi-mars
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ../strapi-mars/app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres
      - reverse-proxy
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.strapi.rule=Host(`strapi.mars-pictures.local`)"
    - "traefik.port=1337"
    networks:
     - default

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi-mars
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    depends_on:
      - reverse-proxy
    volumes:
      - ../data:/var/lib/postgresql/data
    networks:
     - default

  reverse-proxy:
    restart: always
    image: traefik:v2.0
    ports:
    - "443:443"
    - "80:80"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik/traefik.toml:/etc/traefik/traefik.toml
    labels:
    - "traefik.http.routers.api.rule=Host(`traefik.home.local`)"
    - "traefik.http.routers.api.service=api@internal"
    - "traefik.http.routers.api.entrypoints=http"
    networks:
     - default
networks:
  default:
    name: mars-pictures_default
    driver: bridge
  